from django.shortcuts import render, get_object_or_404
# from django.http import Http404
# from django.shortcuts import , render
# Create your views here.
# for more info on urls 

from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic



from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


# By default, the DetailView generic view uses a template called 
# <app name>/<model name>_detail.html. 
# In our case, it would use the template "polls/question_detail.html". The template_name 
# attribute is used to tell Django to use a specific template name instead of the 
# autogenerated default template name. We also specify the template_name for the 
# results list view – this ensures that the results view and the detail view have a 
# different appearance when rendered, even though they’re both a DetailView behind 
# the scenes.

# Similarly, the ListView generic view uses a default template called 
# <app name>/<model name>_list.html; 
# we use template_name to tell ListView to use our existing "polls/index.html" 
# template.

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

"""
IMPORTANT NOTES ON THE ABOVE METHOD FOR VOTE
request.POST is a dictionary-like object that lets you access submitted data by 
key name. request.POST['choice'] returns the ID of the selected choice.

request.POST['choice'] will raise KeyError if choice wasn’t provided in POST data. 
The above code checks for KeyError and redisplays the question form with an 
error message if choice isn’t given.

the code returns an HttpResponseRedirect . HttpResponseRedirect takes a single 
argument: the URL to which the user will be redirected.

We are using the reverse() function in the HttpResponseRedirect constructor in 
this example. This function helps avoid having to hardcode a URL in the view 
function. It is given the name of the view that we want to pass control to and 
the variable portion of the URL pattern that points to that view. In this case, 
using the URLconf we set up in Tutorial 3, this reverse() call will return a 
string like '/polls/3/results/'. where the 3 is the value of question.id. 
This redirected URL will then call the 'results' view to display the final page.
"""